DEVICE_KERNEL_PATH := device/energy/aine-kernel

# Boot Image
BOARD_KERNEL_IMAGE_NAME := Image
TARGET_PREBUILT_DTB    := $(DEVICE_KERNEL_PATH)/dt.img
TARGET_PREBUILT_KERNEL := $(DEVICE_KERNEL_PATH)/zImage

BOARD_KERNEL_BASE := 0x00000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_KERNEL_SECOND_OFFSET := 0x00f00000
BOARD_MKBOOTIMG_ARGS += --ramdisk_offset $(BOARD_RAMDISK_OFFSET)
BOARD_MKBOOTIMG_ARGS += --tags_offset $(BOARD_KERNEL_TAGS_OFFSET)
BOARD_MKBOOTIMG_ARGS += --second_offset $(BOARD_KERNEL_SECOND_OFFSET)
BOARD_MKBOOTIMG_ARGS += --dt $(TARGET_PREBUILT_DTB)
